### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by mhzd** [CCBlueX/AdvanceNoCheat-Issues#2]
Minecraft Server 1.8.8, ProtocolLib3.6.5  
[00:03:33] [Server thread/ERROR]: [AdvanceNoCheat] Unhandled exception occured in onPacketSending(PacketEvent) for AdvanceNoCheat
java.lang.IllegalArgumentException: Object 11 must be of type java.lang.Float
	at com.comphenix.protocol.wrappers.WrappedWatchableObject.setValue(WrappedWatchableObject.java:261) ~[ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.wrappers.WrappedWatchableObject.setValue(WrappedWatchableObject.java:247) ~[ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at _AdvanceNoCheat___________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________1201519995_$1.onPacketSending(AntiDamageIndicator.java:66) ~[AdvanceNoCheat%20v1.9.1.jar:?]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:637) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:613) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.packetQueued(NettyProtocolInjector.java:318) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.compat.netty.independent.NettyProtocolInjector.onPacketSending(NettyProtocolInjector.java:278) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.processSending(NettyChannelInjector.java:401) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector.access$500(NettyChannelInjector.java:82) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.handleScheduled(NettyChannelInjector.java:367) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelInjector$5.onMessageScheduled(NettyChannelInjector.java:335) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.compat.netty.independent.NettyChannelProxy$2.schedulingRunnable(NettyChannelProxy.java:127) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at com.comphenix.protocol.compat.netty.independent.NettyEventLoopProxy.execute(NettyEventLoopProxy.java:95) [ProtocolLib.jar:3.6.5-SNAPSHOT-b214]
	at net.minecraft.server.v1_8_R3.NetworkManager.a(NetworkManager.java:192) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.NetworkManager.handle(NetworkManager.java:141) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.PlayerConnection.sendPacket(PlayerConnection.java:907) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.broadcast(EntityTrackerEntry.java:280) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.broadcastIncludingSelf(EntityTrackerEntry.java:286) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.b(EntityTrackerEntry.java:253) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityTrackerEntry.track(EntityTrackerEntry.java:179) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.EntityTracker.updatePlayers(EntityTracker.java:177) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:803) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [mc.jar:git-Spigot-db6de12-18fbb24]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [mc.jar:git-Spigot-db6de12-18fbb24]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_20]
[00:03:33] [Server thread/ERROR]: Parameters: 
  net.minecraft.server.v1_8_R3.PacketPlayOutEntityMetadata@2cb58ea0[
    a=719
    b=[net.minecraft.server.v1_8_R3.DataWatcher$WatchableObject@17c1df10]
  ]

**Comment by Marco-MC** [comment]
The error is fixed in the 2.0. The 2.0 is current not released. Please wait to the 2.0. You can disable AntiDamageIndicator to prevent your console from this error.
