### ISSUE TITLE
2.1 enable Error 

### ISSUE THREAD

**Issue by Greatliu89** [CCBlueX/AdvanceNoCheat-Issues#7]
[16:50:55] [Server thread/INFO]: Starting minecraft server version 1.10.2
[16:50:55] [Server thread/INFO]: Loading properties
[16:50:55] [Server thread/INFO]: Default game type: SURVIVAL
[16:50:55] [Server thread/INFO]: Generating keypair
[16:50:55] [Server thread/INFO]: Starting Minecraft server on *:25565
[16:50:55] [Server thread/INFO]: Using default channel type
[16:50:55] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-5e5cf84 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)
[16:50:56] [Server thread/INFO]: [CoreProtect] Loading CoreProtect v2.13.1
[16:50:56] [Server thread/INFO]: [SkinsRestorer] Loading SkinsRestorer v12.5.8
[16:50:56] [Server thread/INFO]: [FastAsyncWorldEdit] Loading FastAsyncWorldEdit v16.08.22-3915881-230
[16:50:56] [Server thread/INFO]: [Itembound] Loading Itembound v1.4.1
[16:50:56] [Server thread/INFO]: [PandaWire] Loading PandaWire v1.0.1-SNAPSHOT
[16:50:56] [Server thread/INFO]: [Vault] Loading Vault v1.5.6-b49
[16:50:56] [Server thread/INFO]: [SFWSupport] Loading SFWSupport v1.1
[16:50:56] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.0.2
[16:50:56] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.3;7a097ca
[16:50:56] [Server thread/INFO]: [AdvanceNoCheat] Loading AdvanceNoCheat v2.1
[16:50:56] [Server thread/INFO]: [LockettePro] Loading LockettePro v2.4.1
[16:50:56] [Server thread/INFO]: [Essentials] Loading Essentials v2.0.1-b427
[16:50:56] [Server thread/INFO]: [EssentialsProtect] Loading EssentialsProtect v2.0.1-b427
[16:50:56] [Server thread/INFO]: [EssentialsChat] Loading EssentialsChat v2.0.1-b427
[16:50:56] [Server thread/INFO]: [EssentialsAntiBuild] Loading EssentialsAntiBuild v2.0.1-b427
[16:50:56] [Server thread/INFO]: [OnlineMoney] Loading OnlineMoney v1.0
[16:50:56] [Server thread/INFO]: [EssentialsSpawn] Loading EssentialsSpawn v2.0.1-b427
[16:50:56] [Server thread/INFO]: [FastAsyncWorldEdit] Enabling FastAsyncWorldEdit v16.08.22-3915881-230
[16:50:56] [Server thread/INFO]: [PandaWire] Enabling PandaWire v1.0.1-SNAPSHOT
[16:50:57] [Server thread/INFO]: [Vault] Enabling Vault v1.5.6-b49
[16:50:57] [Server thread/INFO]: [Vault] [Economy] Essentials Economy found: Waiting
[16:50:57] [Server thread/INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[16:50:57] [Server thread/INFO]: [Vault] Enabled Version 1.5.6-b49
[16:50:57] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.0.2
[16:50:57] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[16:50:57] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[16:50:57] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[16:50:57] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[16:50:57] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[16:50:57] [Server thread/INFO]: Preparing level "world"
[16:50:57] [Server thread/INFO]: Preparing start region for level 0 (Seed: 7577803188982267678)
[16:50:58] [Server thread/INFO]: Preparing spawn area: 90%
[16:50:58] [Server thread/INFO]: Preparing start region for level 1 (Seed: 7577803188982267678)
[16:50:59] [Server thread/INFO]: Preparing start region for level 2 (Seed: 7577803188982267678)
[16:50:59] [Server thread/INFO]: [CoreProtect] Enabling CoreProtect v2.13.1
[16:50:59] [Server thread/INFO]: [CoreProtect] CoreProtect has been successfully enabled!
[16:50:59] [Server thread/INFO]: [CoreProtect] Using SQLite for data storage.
[16:50:59] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v12.5.8
[16:50:59] [Server thread/INFO]: [0;32;1mDetected Minecraft [0;33;1mv1_10_R1[0;32;1m, using [0;33;1mUniversalSkinFactory[m
[16:50:59] [Server thread/INFO]: [Itembound] Enabling Itembound v1.4.1
[16:50:59] [Server thread/INFO]: [Itembound] 已调用Vault插件，解绑花费已启用.
[16:50:59] [Server thread/INFO]: [Itembound] 插件已加载
[16:50:59] [Server thread/INFO]: [SFWSupport] Enabling SFWSupport v1.1
[16:50:59] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.3;7a097ca
[16:50:59] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[16:50:59] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_10_R1 as the Bukkit adapter
[16:50:59] [Server thread/INFO]: [AdvanceNoCheat] Enabling AdvanceNoCheat v2.1
[16:50:59] [Server thread/INFO]: [0;31;1m[AdvanceNoCheat] [0;37;22mPlugin is starting.[m
[16:50:59] [Server thread/INFO]: [0;31;1m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m
[16:50:59] [Server thread/INFO]: [0;37;1mPlugin: AdvanceNoCheat[m
[16:50:59] [Server thread/INFO]: [0;37;1mVersion: 2.1[m
[16:50:59] [Server thread/INFO]: [0;37;1mAuthors: [CCBlueX][m
[16:50:59] [Server thread/INFO]: [0;37;1mServer: git-Bukkit-5e5cf84 (MC: 1.10.2)[m
[16:50:59] [Server thread/INFO]: [0;37;1mServer Version: v1_10_R1[m
[16:50:59] [Server thread/INFO]: [0;37;1mNoCheatPlus Installed: No[m
[16:50:59] [Server thread/INFO]: [0;31;1m~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[m
[16:50:59] [Server thread/INFO]: [0;37;1mLoading modules...[m
[16:50:59] [Server thread/ERROR]: Error occurred while enabling AdvanceNoCheat v2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Packet
	at _AdvanceNoCheat__OBFUSCATION_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________4018354596151989877_._(ModuleManager.java:56) ~[?:?]
	at _AdvanceNoCheat__OBFUSCATION_______________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________________4018354596151989877_.<init>(ModuleManager.java:30) ~[?:?]
	at tk.ccbluex.AdvanceNoCheat.AdvanceNoCheat.onEnable(AdvanceNoCheat.java:103) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[craftbukkit.jar:git-Bukkit-5e5cf84]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:347) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:319) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:404) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:369) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:324) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:243) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:514) [craftbukkit.jar:git-Bukkit-5e5cf84]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_73]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67) ~[craftbukkit.jar:git-Bukkit-5e5cf84]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62) ~[craftbukkit.jar:git-Bukkit-5e5cf84]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_73]
	... 14 more
[16:50:59] [Server thread/INFO]: [LockettePro] Enabling LockettePro v2.4.1
[16:50:59] [Server thread/INFO]: [Essentials] Enabling Essentials v2.0.1-b427
[16:50:59] [Server thread/INFO]: Using locale zh_CN
[16:50:59] [Server thread/INFO]: [Essentials] Using 1.8.3+ BlockStateMeta provider as mob spawner provider.
[16:50:59] [Server thread/INFO]: [Essentials] Using Reflection based provider as spawn egg provider.
[16:50:59] [Server thread/INFO]: [Essentials] Using 1.9+ BasePotionData provider as potion meta provider.
[16:50:59] [Server thread/INFO]: Using locale zh_CN
[16:50:59] [Server thread/INFO]: [Essentials] Starting Metrics. Opt-out using the global PluginMetrics config.
[16:50:59] [Server thread/INFO]: [Vault][Economy] Essentials Economy hooked.
[16:50:59] [Server thread/INFO]: [Essentials] Using config file enhanced permissions.
[16:50:59] [Server thread/INFO]: [Essentials] Permissions listed in as player-commands will be given to all users.
[16:50:59] [Server thread/INFO]: [EssentialsProtect] Enabling EssentialsProtect v2.0.1-b427
[16:50:59] [Server thread/INFO]: [EssentialsChat] Enabling EssentialsChat v2.0.1-b427
[16:50:59] [Server thread/INFO]: [EssentialsAntiBuild] Enabling EssentialsAntiBuild v2.0.1-b427
[16:50:59] [Server thread/INFO]: [OnlineMoney] Enabling OnlineMoney v1.0
[16:50:59] [Server thread/INFO]: [EssentialsSpawn] Enabling EssentialsSpawn v2.0.1-b427
[16:50:59] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:50:59] [Server thread/INFO]: Done (2.783s)! For help, type "help" or "?"

2.1 plugin can't run 
2.0 is usable

**Comment by Marco-MC** [comment]
Fixed. :)
